package Formularios;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computer
 */
public class Nueva_lista_productos extends javax.swing.JFrame {

       public Image geticonimage()
    {
     Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("nuevas imagenes/pp.jpg"));
    return retValue;
    }

    public ArrayList<String>lista;
    Adm_sql sql;
    String f2="";
    public String usuario;
//    ArrayList<String>lista;
    public Nueva_lista_productos() 
    {
        initComponents();
        try {
             this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("iMarket");
        Date fecha=new Date();
        String[]vector;
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
         f2=formateador.format(fecha);
         
         
         
         
//         sql=new Adm_sql();
         //lista=new ArrayList<String>();
         //JOptionPane.showMessageDialog(null, usuario);
//         lista=sql.consultarlista(usuario, f2);
//         String cadena=sql.leerproductos3(lista.get(0));
//         vector=cadena.split(";");
//         lblpro1.setText(vector[0]);
//         lblprecio1.setText(vector[1]);
         
//        String[]vector;
//        String[]vector2;
//        //lista=new ArrayList<String>();
//        vector=lista.get(0).split(";");
//        vector2= sql.leerpro(vector[1]).split(";");
//        lblpro1.setText(vector2[0]);
//        lblprecio1.setText(vector2[1]);
//        h(lblfoto1,vector[2]);
        //lista=new ArrayList<String>();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
       
        
    }
    
     public void h(JLabel j,String c){
        try {
            ArrayList<Image> listaimg= sql.imagproductos(c); 
            Image foto=null;
            Icon ico=null;
            foto=listaimg.get(0);
            ico=new ImageIcon(foto.getScaledInstance(j.getWidth(),  j.getHeight(), Image.SCALE_DEFAULT));
            j.setIcon(ico);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
            
            //w.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblfoto3 = new javax.swing.JLabel();
        lblfoto2 = new javax.swing.JLabel();
        lblfoto1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        lblpro3 = new javax.swing.JLabel();
        lblprecio3 = new javax.swing.JLabel();
        lblpro2 = new javax.swing.JLabel();
        lblprecio2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        lblpro1 = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        lblfoto6 = new javax.swing.JLabel();
        lblfoto5 = new javax.swing.JLabel();
        lblfoto4 = new javax.swing.JLabel();
        lblpro6 = new javax.swing.JLabel();
        lblprecio6 = new javax.swing.JLabel();
        bnt6 = new javax.swing.JButton();
        lblpro5 = new javax.swing.JLabel();
        lblprecio5 = new javax.swing.JLabel();
        bnt5 = new javax.swing.JButton();
        lblpro4 = new javax.swing.JLabel();
        lblprecio4 = new javax.swing.JLabel();
        btn4 = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        scrollbar1 = new java.awt.Scrollbar();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.pink);
        setIconImage(geticonimage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/embu.jpg"))); // NOI18N
        jPanel1.add(lblfoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 70, -1, -1));

        lblfoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foco.jpg"))); // NOI18N
        jPanel1.add(lblfoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 70, -1, -1));

        lblfoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pollito.jpg"))); // NOI18N
        jPanel1.add(lblfoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 190, 28, -1));

        lblpro3.setText("jLabel12");
        jPanel1.add(lblpro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 136, 52, -1));

        lblprecio3.setText("jLabel15");
        jPanel1.add(lblprecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 161, 52, -1));

        lblpro2.setText("jLabel11");
        jPanel1.add(lblpro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 140, 52, -1));

        lblprecio2.setText("jLabel14");
        jPanel1.add(lblprecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 165, 52, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 186, 28, -1));

        lblpro1.setText("jLabel10");
        jPanel1.add(lblpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 52, -1));

        lblprecio1.setText("jLabel13");
        jPanel1.add(lblprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 52, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 28, -1));

        lblfoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lagosta.jpg"))); // NOI18N
        jPanel1.add(lblfoto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 258, -1, -1));

        lblfoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vinito.jpg"))); // NOI18N
        jPanel1.add(lblfoto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 258, -1, -1));

        lblfoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pancito.jpg"))); // NOI18N
        jPanel1.add(lblfoto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, -1, -1));

        lblpro6.setText("jLabel18");
        jPanel1.add(lblpro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 321, 52, -1));

        lblprecio6.setText("jLabel21");
        jPanel1.add(lblprecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 341, 52, -1));

        bnt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        bnt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bnt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 366, 28, -1));

        lblpro5.setText("jLabel17");
        jPanel1.add(lblpro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 321, 52, -1));

        lblprecio5.setText("jLabel20");
        jPanel1.add(lblprecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 341, 52, -1));

        bnt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        bnt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bnt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 366, 28, -1));

        lblpro4.setText("jLabel16");
        jPanel1.add(lblpro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 321, 52, -1));

        lblprecio4.setText("jLabel19");
        jPanel1.add(lblprecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 341, 52, -1));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 366, 28, -1));

        lblusuario.setText("Alvaro Emiliano");
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 142, 34));

        lblfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.jpg"))); // NOI18N
        jPanel1.add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 34));

        jLabel1.setText("Lista de Compras");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 4, 111, 34));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 35, 34));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 560, 10));
        jPanel1.add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 20, 339));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 450, 450));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Nombre");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 56, 22));

        jLabel23.setText("Cantidad");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 56, 22));

        jLabel24.setText("V.Unit");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 56, 22));

        jLabel25.setText("Detalles de Precios");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, -1, -1));

        jLabel26.setText("Valor Total");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 76, 31));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 115, 31));

        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 38));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 38));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 10, 390, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Principal_productos l =new Principal_productos();
     l.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void bnt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt5ActionPerformed

    private void bnt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nueva_lista_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nueva_lista_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nueva_lista_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nueva_lista_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nueva_lista_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt5;
    private javax.swing.JButton bnt6;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lblfoto;
    public javax.swing.JLabel lblfoto1;
    public javax.swing.JLabel lblfoto2;
    public javax.swing.JLabel lblfoto3;
    public javax.swing.JLabel lblfoto4;
    public javax.swing.JLabel lblfoto5;
    public javax.swing.JLabel lblfoto6;
    public javax.swing.JLabel lblprecio1;
    public javax.swing.JLabel lblprecio2;
    public javax.swing.JLabel lblprecio3;
    public javax.swing.JLabel lblprecio4;
    public javax.swing.JLabel lblprecio5;
    public javax.swing.JLabel lblprecio6;
    public javax.swing.JLabel lblpro1;
    public javax.swing.JLabel lblpro2;
    public javax.swing.JLabel lblpro3;
    public javax.swing.JLabel lblpro4;
    public javax.swing.JLabel lblpro5;
    public javax.swing.JLabel lblpro6;
    public javax.swing.JLabel lblusuario;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
