package Formularios;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LuisSolorzano
 */
public class Principal_productos extends javax.swing.JFrame {

    


    /**
     * Creates new form Principal
     * @return 
     */
    
   
       public Image geticonimage()
    {
     Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("nuevas imagenes/pp.jpg"));
    return retValue;
    }
    public String usuario="";
    Adm_sql sql;
    public Principal_productos() {
        initComponents();
         this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("iMarket");
        lblusuario.setText(usuario);
        sql=new Adm_sql();
        Adm_sql producto=new Adm_sql();
        Autocomplete a=new Autocomplete();
        a.setupAutoComplete(jTextField1, producto.leerproductos());
       ocultar();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblimg1 = new javax.swing.JLabel();
        lblimg2 = new javax.swing.JLabel();
        lblimg3 = new javax.swing.JLabel();
        lblimg4 = new javax.swing.JLabel();
        lblimg5 = new javax.swing.JLabel();
        lblimg6 = new javax.swing.JLabel();
        lblnom1 = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        lblnom5 = new javax.swing.JLabel();
        lblnom3 = new javax.swing.JLabel();
        lblnom4 = new javax.swing.JLabel();
        lblnom2 = new javax.swing.JLabel();
        lblnom6 = new javax.swing.JLabel();
        lblprecio5 = new javax.swing.JLabel();
        lblprecio4 = new javax.swing.JLabel();
        lblprecio3 = new javax.swing.JLabel();
        lblprecio2 = new javax.swing.JLabel();
        lblprecio6 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setIconImage(geticonimage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, 30));

        jButton2.setText("Carnes y Embutidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 200, 40));

        jButton3.setText("Ferreteria");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 40));

        jButton4.setText("Frutas y Verduras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 173, 200, 40));

        jButton6.setText("Bebidas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 223, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ferre.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnes.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frutas.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebidas.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 243, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 253, 10));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setText("Listas de Compras ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 203, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 360));

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("Ferreteria");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 580, 60));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carr.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 80, 60));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevas imagenes/ss.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taladro.jpg"))); // NOI18N
        jPanel3.add(lblimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        lblimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llavetubo.jpg"))); // NOI18N
        jPanel3.add(lblimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 54, -1));

        lblimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pintura.jpg"))); // NOI18N
        jPanel3.add(lblimg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foco.jpg"))); // NOI18N
        jPanel3.add(lblimg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/martillo.jpg"))); // NOI18N
        jPanel3.add(lblimg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 157, -1, -1));

        lblimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/desarmadores.jpg"))); // NOI18N
        jPanel3.add(lblimg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 162, -1, 45));

        lblnom1.setText("Descripcion");
        jPanel3.add(lblnom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 69, -1, -1));

        lblprecio1.setText("Precio");
        jPanel3.add(lblprecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 89, -1, -1));

        lblnom5.setText("Descripcion");
        jPanel3.add(lblnom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 215, -1, -1));

        lblnom3.setText("Descripcion");
        jPanel3.add(lblnom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 69, -1, -1));

        lblnom4.setText("Descripcion");
        jPanel3.add(lblnom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 215, -1, -1));

        lblnom2.setText("Descripcion");
        jPanel3.add(lblnom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 69, -1, -1));

        lblnom6.setText("Descripcion");
        jPanel3.add(lblnom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 213, -1, -1));

        lblprecio5.setText("Precio");
        jPanel3.add(lblprecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 235, -1, -1));

        lblprecio4.setText("Precio");
        jPanel3.add(lblprecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 235, -1, -1));

        lblprecio3.setText("Precio");
        jPanel3.add(lblprecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 89, -1, -1));

        lblprecio2.setText("Precio");
        jPanel3.add(lblprecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 89, -1, -1));

        lblprecio6.setText("Precio");
        jPanel3.add(lblprecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 233, -1, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jPanel3.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 109, 43, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jPanel3.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 109, 43, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 109, 43, -1));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jPanel3.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 258, 43, -1));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jPanel3.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 258, 43, -1));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jPanel3.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 258, 43, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sigui.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 40, 30));

        jLabel2.setText("Siguiente");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 300));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 460, 330));

        jButton15.setText("Guardar producto a la lista");
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 450, -1));

        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigo="3333";
        ocultar();
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("3333");
        ArrayList<Image> listaimg= sql.imagproductos("3333");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Nueva_lista_productos j =new Nueva_lista_productos();
       j.show();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Iniciar_sesion hola=new Iniciar_sesion();
        hola.show();
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         mostrar();
        try {
            String codigo="1111";
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("1111");
        ArrayList<Image> listaimg= sql.imagproductos("1111");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        
       

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    public void h(JLabel j,String c){
        try {
            ArrayList<Image> listaimg= sql.imagproductos(c); 
            Image foto=null;
            Icon ico=null;
            foto=listaimg.get(0);
            ico=new ImageIcon(foto.getScaledInstance(j.getWidth(),  j.getHeight(), Image.SCALE_DEFAULT));
            j.setIcon(ico);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
            
            //w.updateUI();
    }
    
    public void ocultar(){
        lblimg1.setVisible(false);
        lblimg2.setVisible(false);
        lblimg3.setVisible(false);
        lblimg4.setVisible(false);
        lblimg5.setVisible(false);
        lblimg6.setVisible(false);
        lblnom1.setVisible(false);
        lblnom2.setVisible(false);
        lblnom3.setVisible(false);
        lblnom4.setVisible(false);
        lblnom5.setVisible(false);
        lblnom6.setVisible(false);
        lblimg2.setVisible(false);
        lblimg3.setVisible(false);
        lblimg4.setVisible(false);
        lblimg5.setVisible(false);
        lblimg6.setVisible(false);
        lblprecio1.setVisible(false);
        lblprecio2.setVisible(false);
        lblprecio3.setVisible(false);
        lblprecio4.setVisible(false);
        lblprecio5.setVisible(false);
        lblprecio6.setVisible(false);
        btn1.setVisible(false);
        btn2.setVisible(false);
        btn3.setVisible(false);
        btn4.setVisible(false);
        btn5.setVisible(false);
        btn6.setVisible(false);
        
    }
    
    public void mostrar(){
        lblimg1.setVisible(true);
        lblimg2.setVisible(true);
        lblimg3.setVisible(true);
        lblimg4.setVisible(true);
        lblimg5.setVisible(true);
        lblimg6.setVisible(true);
        lblnom1.setVisible(true);
        lblnom2.setVisible(true);
        lblnom3.setVisible(true);
        lblnom4.setVisible(true);
        lblnom5.setVisible(true);
        lblnom6.setVisible(true);
        lblimg2.setVisible(true);
        lblimg3.setVisible(true);
        lblimg4.setVisible(true);
        lblimg5.setVisible(true);
        lblimg6.setVisible(true);
        lblprecio1.setVisible(true);
        lblprecio2.setVisible(true);
        lblprecio3.setVisible(true);
        lblprecio4.setVisible(true);
        lblprecio5.setVisible(true);
        lblprecio6.setVisible(true);
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ocultar();
        String codigo="2222";
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("2222");
        ArrayList<Image> listaimg= sql.imagproductos("2222");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String codigo="4444";
        ocultar();
       
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("4444");
        ArrayList<Image> listaimg= sql.imagproductos("4444");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JLabel lblimg3;
    private javax.swing.JLabel lblimg4;
    private javax.swing.JLabel lblimg5;
    private javax.swing.JLabel lblimg6;
    private javax.swing.JLabel lblnom1;
    private javax.swing.JLabel lblnom2;
    private javax.swing.JLabel lblnom3;
    private javax.swing.JLabel lblnom4;
    private javax.swing.JLabel lblnom5;
    private javax.swing.JLabel lblnom6;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lblprecio2;
    private javax.swing.JLabel lblprecio3;
    private javax.swing.JLabel lblprecio4;
    private javax.swing.JLabel lblprecio5;
    private javax.swing.JLabel lblprecio6;
    public javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
