package Formularios;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LuisSolorzano
 */
public class Principal_productos extends javax.swing.JFrame {

    


    /**
     * Creates new form Principal
     * @return 
     */
    
   
       public Image geticonimage()
    {
     Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("nuevas imagenes/pp.jpg"));
    return retValue;
    }
    public String usuario="";
    public String id="";
    Adm_sql sql;
    Date fecha;
    String f2="";
    ArrayList<String>lista;
    public Principal_productos() {
        initComponents();
         this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("iMarket");
        lblusuario.setText(usuario);
        sql=new Adm_sql();
        setJTexFieldChanged(txtflitro);
        Adm_sql producto=new Adm_sql();
        Autocomplete a=new Autocomplete();
        a.setupAutoComplete(txtflitro, producto.leerproductos());
        lista=new ArrayList<String>();
        lblid1.setVisible(false);
        lblid2.setVisible(false);
        lblid3.setVisible(false);
        lblid4.setVisible(false);
        lblid5.setVisible(false);
        lblid6.setVisible(false);
        fecha=new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        f2=formateador.format(fecha);
        System.out.print(id);
       ocultar();
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtflitro = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jpanelcont1 = new javax.swing.JPanel();
        lblimg1 = new javax.swing.JLabel();
        lblnom1 = new javax.swing.JLabel();
        lblprecio1 = new javax.swing.JLabel();
        lblid1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jpanelcont6 = new javax.swing.JPanel();
        lblimg6 = new javax.swing.JLabel();
        lblnom6 = new javax.swing.JLabel();
        lblprecio6 = new javax.swing.JLabel();
        lblid6 = new javax.swing.JLabel();
        btn6 = new javax.swing.JButton();
        jpanelcont5 = new javax.swing.JPanel();
        lblimg5 = new javax.swing.JLabel();
        lblnom5 = new javax.swing.JLabel();
        lblprecio5 = new javax.swing.JLabel();
        lblid5 = new javax.swing.JLabel();
        btn5 = new javax.swing.JButton();
        jpanelcont4 = new javax.swing.JPanel();
        lblimg4 = new javax.swing.JLabel();
        lblnom4 = new javax.swing.JLabel();
        lblprecio4 = new javax.swing.JLabel();
        lblid4 = new javax.swing.JLabel();
        btn4 = new javax.swing.JButton();
        jpanelcont3 = new javax.swing.JPanel();
        lblimg3 = new javax.swing.JLabel();
        lblnom3 = new javax.swing.JLabel();
        lblprecio3 = new javax.swing.JLabel();
        lblid3 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jpanelcont2 = new javax.swing.JPanel();
        lblimg2 = new javax.swing.JLabel();
        lblnom2 = new javax.swing.JLabel();
        lblprecio2 = new javax.swing.JLabel();
        lblid2 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpanelcont7 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setIconImage(geticonimage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");
        jPanel1.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, 30));

        jButton2.setText("Carnes y Embutidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 200, 40));

        jButton3.setText("Ferreteria");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 40));

        jButton4.setText("Frutas y Verduras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 173, 200, 40));

        jButton6.setText("Bebidas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 223, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ferre.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnes.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frutas.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebidas.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 243, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 253, 10));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setText("Listas de Compras ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 203, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 360));

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("Ferreteria");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 30));

        txtflitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflitroActionPerformed(evt);
            }
        });
        txtflitro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtflitroKeyTyped(evt);
            }
        });
        jPanel2.add(txtflitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 580, 60));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carr.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 80, 60));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevas imagenes/ss.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taladro.jpg"))); // NOI18N
        jpanelcont1.add(lblimg1);

        lblnom1.setText("Descripcion");
        jpanelcont1.add(lblnom1);

        lblprecio1.setText("Precio");
        jpanelcont1.add(lblprecio1);

        lblid1.setText("jLabel10");
        jpanelcont1.add(lblid1);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jpanelcont1.add(btn1);

        jPanel3.add(jpanelcont1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 130));

        lblimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/desarmadores.jpg"))); // NOI18N
        jpanelcont6.add(lblimg6);

        lblnom6.setText("Descripcion");
        jpanelcont6.add(lblnom6);

        lblprecio6.setText("Precio");
        jpanelcont6.add(lblprecio6);

        lblid6.setText("jLabel15");
        jpanelcont6.add(lblid6);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jpanelcont6.add(btn6);

        jPanel3.add(jpanelcont6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 130));

        lblimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/martillo.jpg"))); // NOI18N
        jpanelcont5.add(lblimg5);

        lblnom5.setText("Descripcion");
        jpanelcont5.add(lblnom5);

        lblprecio5.setText("Precio");
        jpanelcont5.add(lblprecio5);

        lblid5.setText("jLabel14");
        jpanelcont5.add(lblid5);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jpanelcont5.add(btn5);

        jPanel3.add(jpanelcont5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, 140));

        lblimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foco.jpg"))); // NOI18N
        jpanelcont4.add(lblimg4);

        lblnom4.setText("Descripcion");
        jpanelcont4.add(lblnom4);

        lblprecio4.setText("Precio");
        jpanelcont4.add(lblprecio4);

        lblid4.setText("jLabel13");
        jpanelcont4.add(lblid4);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jpanelcont4.add(btn4);

        jPanel3.add(jpanelcont4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 140));

        lblimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pintura.jpg"))); // NOI18N
        jpanelcont3.add(lblimg3);

        lblnom3.setText("Descripcion");
        jpanelcont3.add(lblnom3);

        lblprecio3.setText("Precio");
        jpanelcont3.add(lblprecio3);

        lblid3.setText("jLabel12");
        jpanelcont3.add(lblid3);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jpanelcont3.add(btn3);

        jPanel3.add(jpanelcont3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, 130));

        lblimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llavetubo.jpg"))); // NOI18N
        jpanelcont2.add(lblimg2);

        lblnom2.setText("Descripcion");
        jpanelcont2.add(lblnom2);

        lblprecio2.setText("Precio");
        jpanelcont2.add(lblprecio2);

        lblid2.setText("jLabel11");
        jpanelcont2.add(lblid2);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jpanelcont2.add(btn2);

        jPanel3.add(jpanelcont2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, 140));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sigui.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 40, 30));

        jLabel2.setText("Siguiente");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 310));
        jPanel3.add(jpanelcont7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 130));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 460, 330));

        jButton15.setText("Guardar producto a la lista");
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 450, -1));

        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigo="3333";
        ocultar();
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("3333");
        ArrayList<Image> listaimg= sql.imagproductos("3333");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    private void setJTexFieldChanged(JTextField txt){
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent,txt);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent,txt);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent,txt);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    }
    private void printIt(DocumentEvent documentEvent,JTextField txt ) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
 
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
            txtEjemploJTextFieldChanged(txt);
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            txtEjemploJTextFieldChanged(txt);
        }
    }
    private void txtEjemploJTextFieldChanged(JTextField txt){
        filtro(txt);
    }
    int avi=0;
    private void filtro(JTextField txt){
        //mostrar();
        if (txt.getText() == null ? lblnom1.getText() == null : txt.getText().equals(lblnom1.getText())) {
            avi=1;
            jpanelcont2.setVisible(false);
            
            jpanelcont1.setVisible(false);
            jpanelcont7.add(lblimg1);
             jpanelcont7.add(lblnom1);
            jpanelcont7.add(lblprecio1);
            jpanelcont7.add(btn1);
            jpanelcont7.setVisible(true);
            
            
             jpanelcont3.setVisible(false);
           
            jpanelcont4.setVisible(false);
             
//          
             jpanelcont5.setVisible(false);
            
              jpanelcont6.setVisible(false);
            
        }
        else{
            if (txt.getText() == null ? lblnom2.getText() == null : txt.getText().equals(lblnom2.getText())) {
            avi=2;
            jpanelcont1.setVisible(false);
            
            jpanelcont2.setVisible(false);
            jpanelcont7.add(lblimg2);
             jpanelcont7.add(lblnom2);
            jpanelcont7.add(lblprecio2);
            jpanelcont7.add(btn2);
            jpanelcont7.setVisible(true);
            
//            
            jpanelcont3.setVisible(false);
            
//           
             jpanelcont4.setVisible(false);
            
//           
              jpanelcont5.setVisible(false);            

//            
              jpanelcont6.setVisible(false);
            //lblimg4.revalidate();
        }
            else{
                if (txt.getText() == null ? lblnom3.getText() == null : txt.getText().equals(lblnom3.getText())) {
                  avi=3;  
              jpanelcont1.setVisible(false);
            
              jpanelcont2.setVisible(false);
              
              jpanelcont3.setVisible(false);
            jpanelcont7.add(lblimg3);
             jpanelcont7.add(lblnom3);
            jpanelcont7.add(lblprecio3);
            jpanelcont7.add(btn3);
            jpanelcont7.setVisible(true);
            
              
             jpanelcont4.setVisible(false);
            
//           
              jpanelcont5.setVisible(false);            

//           
              jpanelcont6.setVisible(false);
            //lblimg4.revalidate();
        }
                else{
                    if (txt.getText() == null ? lblnom4.getText() == null : txt.getText().equals(lblnom4.getText())) {
                  avi=4;
              jpanelcont1.setVisible(false);
            
              jpanelcont3.setVisible(false);
              
              jpanelcont4.setVisible(false);
            jpanelcont7.add(lblimg4);
             jpanelcont7.add(lblnom4);
            jpanelcont7.add(lblprecio4);
            jpanelcont7.add(btn4);
            jpanelcont7.setVisible(true);
            
              
              jpanelcont2.setVisible(false);
            
//           
              jpanelcont5.setVisible(false);
            
//           
              jpanelcont6.setVisible(false);
            //lblimg4.revalidate();
        }
                    else{
                        
                        if (txt.getText() == null ? lblnom5.getText() == null : txt.getText().equals(lblnom5.getText())) {
                       avi=5;
              jpanelcont1.setVisible(false);
            
              jpanelcont3.setVisible(false);
            
              jpanelcont5.setVisible(false);
            jpanelcont7.add(lblimg5);
             jpanelcont7.add(lblnom5);
            jpanelcont7.add(lblprecio5);
            jpanelcont7.add(btn5);
            jpanelcont7.setVisible(true);
            
               jpanelcont4.setVisible(false);
            
              jpanelcont2.setVisible(false);
            
//            

              jpanelcont6.setVisible(false);
            //lblimg4.revalidate();
        }
                        else{
                            if (txt.getText() == null ? lblnom6.getText() == null : txt.getText().equals(lblnom6.getText())) {
                         avi=6;
             jpanelcont1.setVisible(false);
            
              jpanelcont3.setVisible(false);
            
              jpanelcont6.setVisible(false);
            jpanelcont7.add(lblimg6);
             jpanelcont7.add(lblnom6);
            jpanelcont7.add(lblprecio6);
            jpanelcont7.add(btn6);
            jpanelcont7.setVisible(true);
            
               jpanelcont4.setVisible(false);
            
//           
              jpanelcont5.setVisible(false);
            
//           
              jpanelcont2.setVisible(false);
            //lblimg4.revalidate();
        }
                            else{
                                if (avi==1) {
                                    jpanelcont1.removeAll();
                                    jpanelcont1.add(lblimg1);
                                    jpanelcont1.add(lblnom1);
                                    jpanelcont1.add(lblprecio1);
                                    jpanelcont1.add(btn1);
                                }
                                else{
                                    if (avi==2) {
                                        jpanelcont2.removeAll();
                                        jpanelcont2.add(lblimg2);
                                        jpanelcont2.add(lblnom2);
                                        jpanelcont2.add(lblprecio2);
                                        jpanelcont2.add(btn2);
                                    }
                                    else{
                                        if (avi==3) {
                                            jpanelcont3.removeAll();
                                            jpanelcont3.add(lblimg3);
                                            jpanelcont3.add(lblnom3);
                                            jpanelcont3.add(lblprecio3);
                                            jpanelcont3.add(btn3);
                                        }
                                        else{
                                            if (avi==4) {
                                                jpanelcont4.removeAll();
                                               jpanelcont4.add(lblimg4);
                                               jpanelcont4.add(lblnom4);
                                               jpanelcont4.add(lblprecio4);
                                               jpanelcont4.add(btn4);
                                            }
                                            else{
                                                if (avi==5) {
                                                    jpanelcont5.removeAll();
                                                    jpanelcont5.add(lblimg5);
                                                   jpanelcont5.add(lblnom5);
                                                  jpanelcont5.add(lblprecio5);
                                                  jpanelcont5.add(btn5);
                                                }
                                                else{
                                                    if (avi==6) {
                                                        jpanelcont6.removeAll();
                                                        jpanelcont6.add(lblimg6);
                                                        jpanelcont6.add(lblnom6);
                                                        jpanelcont6.add(lblprecio6);
                                                        jpanelcont6.add(btn6);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    
                                }
                                mostrar(); 
                            }
                        }
                    }
                    
                }
               
            }
        }
    }
    
    
    private void txtflitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtflitroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String[]vector;
             Nueva_lista_productos j =new Nueva_lista_productos();
             this.setVisible(false); 
        j.show();
       j.lista=this.lista;
       j.lblusuario.setText(lblusuario.getText());
       //JOptionPane.showMessageDialog(null, id);
       j.usuario=id;
       Image foto=sql.getfoto(id);
            Icon ico=new ImageIcon(foto.getScaledInstance(j.lblfoto.getWidth(),  j.lblfoto.getHeight(), Image.SCALE_DEFAULT));
            j.lblfoto.setIcon(ico);
            j.lblfoto.updateUI();
       lista=sql.consultarlista(id, f2);
         String cadena=sql.leerproductos3(lista.get(0));
         vector=cadena.split(";");
         j.lblpro1.setText(vector[0]);
         j.lblprecio1.setText(vector[1]);
         h(j.lblfoto1,vector[2]);
         
         cadena=sql.leerproductos3(lista.get(1));
         vector=cadena.split(";");
         j.lblpro2.setText(vector[0]);
         j.lblprecio2.setText(vector[1]);
         h(j.lblfoto2,vector[2]);
         
         cadena=sql.leerproductos3(lista.get(2));
         vector=cadena.split(";");
         j.lblpro3.setText(vector[0]);
         j.lblprecio3.setText(vector[1]);
         h(j.lblfoto3,vector[2]);
         
          cadena=sql.leerproductos3(lista.get(3));
         vector=cadena.split(";");
         j.lblpro4.setText(vector[0]);
         j.lblprecio4.setText(vector[1]);
         h(j.lblfoto4,vector[2]);
         
         cadena=sql.leerproductos3(lista.get(4));
         vector=cadena.split(";");
         j.lblpro5.setText(vector[0]);
         j.lblprecio5.setText(vector[1]);
         h(j.lblfoto5,vector[2]);
         
         cadena=sql.leerproductos3(lista.get(5));
         vector=cadena.split(";");
         j.lblpro6.setText(vector[0]);
         j.lblprecio6.setText(vector[1]);
         h(j.lblfoto6,vector[2]);

       
        
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Iniciar_sesion hola=new Iniciar_sesion();
        hola.show();
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void txtflitroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtflitroKeyTyped
        
    }//GEN-LAST:event_txtflitroKeyTyped

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
//          lista.add(" "+id+";"+" "+lblid1+";"+" "+f2);
         
         try {
             
             int idnum2=Integer.parseInt(lblid1.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         mostrar();
        try {
            String codigo="1111";
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("1111");
        ArrayList<Image> listaimg= sql.imagproductos("1111");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        lblid1.setText(vector[2]);
        
        
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        lblid2.setText(vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        lblid3.setText(vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        lblid4.setText(vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        lblid5.setText(vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        lblid6.setText(vector[2]);
        
       

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    public void h(JLabel j,String c){
        try {
            ArrayList<Image> listaimg= sql.imagproductos(c); 
            Image foto=null;
            Icon ico=null;
            foto=listaimg.get(0);
            ico=new ImageIcon(foto.getScaledInstance(j.getWidth(),  j.getHeight(), Image.SCALE_DEFAULT));
            j.setIcon(ico);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
            
            //w.updateUI();
    }
    
    public void ocultar(){

          jpanelcont1.setVisible(false);
          jpanelcont2.setVisible(false);
          jpanelcont3.setVisible(false);
          jpanelcont4.setVisible(false);
          jpanelcont5.setVisible(false);
          jpanelcont6.setVisible(false);
          jpanelcont7.setVisible(false);
    }
    
    public void mostrar(){
        jpanelcont7.removeAll();
          jpanelcont7.setVisible(false);     
          jpanelcont1.setVisible(true);
          jpanelcont2.setVisible(true);
          jpanelcont3.setVisible(true);
          jpanelcont4.setVisible(true);
          jpanelcont5.setVisible(true);
          jpanelcont6.setVisible(true);
          
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ocultar();
        String codigo="2222";
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("2222");
        ArrayList<Image> listaimg= sql.imagproductos("2222");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String codigo="4444";
        ocultar();
       
        String[]vector;
        ArrayList<String> lista= sql.leerproductos2("4444");
        ArrayList<Image> listaimg= sql.imagproductos("4444");

        vector=lista.get(0).split(";");
        lblnom1.setText(vector[0]);
        lblprecio1.setText(vector[1]);
        h(lblimg1,vector[2]);
        
        vector=lista.get(1).split(";");
        lblnom2.setText(vector[0]);
        lblprecio2.setText(vector[1]);
        h(lblimg2,vector[2]);
        
        vector=lista.get(2).split(";");
        lblnom3.setText(vector[0]);
        lblprecio3.setText(vector[1]);
        h(lblimg3,vector[2]);
        
        vector=lista.get(3).split(";");
        lblnom4.setText(vector[0]);
        lblprecio4.setText(vector[1]);
        h(lblimg4,vector[2]);
        
        vector=lista.get(4).split(";");
        lblnom5.setText(vector[0]);
        lblprecio5.setText(vector[1]);
        h(lblimg5,vector[2]);
        
        vector=lista.get(5).split(";");
        lblnom6.setText(vector[0]);
        lblprecio6.setText(vector[1]);
        h(lblimg6,vector[2]);
        mostrar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
         //lista.add(" "+id+";"+" "+lblid2+";"+" "+f2);
         try {
             
             int idnum2=Integer.parseInt(lblid2.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
//        lista.add(" "+id+";"+" "+lblid3+";"+" "+f2);

         try {
             
             int idnum2=Integer.parseInt(lblid3.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
//        lista.add(" "+id+";"+" "+lblid4+";"+" "+f2);

          try {
             
             int idnum2=Integer.parseInt(lblid4.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
//        lista.add(" "+id+";"+" "+lblid5+";"+" "+f2);
         try {
             
             int idnum2=Integer.parseInt(lblid5.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
//        lista.add(" "+id+";"+" "+lblid6+";"+" "+f2);

         try {
             
             int idnum2=Integer.parseInt(lblid6.getText(),16);
            //sql.llenartablalista(Integer.parseInt(id,16), Integer.parseInt(lblid1.getText(),16),f2);
            sql.llenartablalista(id, idnum2,f2);
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpanelcont1;
    private javax.swing.JPanel jpanelcont2;
    private javax.swing.JPanel jpanelcont3;
    private javax.swing.JPanel jpanelcont4;
    private javax.swing.JPanel jpanelcont5;
    private javax.swing.JPanel jpanelcont6;
    private javax.swing.JPanel jpanelcont7;
    private javax.swing.JLabel lblid1;
    private javax.swing.JLabel lblid2;
    private javax.swing.JLabel lblid3;
    private javax.swing.JLabel lblid4;
    private javax.swing.JLabel lblid5;
    private javax.swing.JLabel lblid6;
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JLabel lblimg3;
    private javax.swing.JLabel lblimg4;
    private javax.swing.JLabel lblimg5;
    private javax.swing.JLabel lblimg6;
    private javax.swing.JLabel lblnom1;
    private javax.swing.JLabel lblnom2;
    private javax.swing.JLabel lblnom3;
    private javax.swing.JLabel lblnom4;
    private javax.swing.JLabel lblnom5;
    private javax.swing.JLabel lblnom6;
    private javax.swing.JLabel lblprecio1;
    private javax.swing.JLabel lblprecio2;
    private javax.swing.JLabel lblprecio3;
    private javax.swing.JLabel lblprecio4;
    private javax.swing.JLabel lblprecio5;
    private javax.swing.JLabel lblprecio6;
    public javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtflitro;
    // End of variables declaration//GEN-END:variables
}
