/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computer
 */
public class presentacion extends javax.swing.JPanel {

    /**
     * Creates new form presentacion
     */
    public presentacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.orange);
        jLabel3.setText("iMARKET");
        add(jLabel3);
        jLabel3.setBounds(170, 170, 120, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\matrix\\Desktop\\fondo1.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 571, 377);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
